$$Exercise: 1$$

In this lab, we will consider non-linear problems which can be converted to linear programs. One famous example is the absolute value function given as: 
\begin{align}
|x| = \begin{cases}
        x  & \text{ if } x\geq 0 \\ 
        -x & \text{ otherwise }.
      \end{cases}
\end{align}

We will now consider the absolute value function appearing in the objective function. Consider the optimization problem $\textbf{(OP)}$:
\begin{align}
\min \ |x_1| + |x_2| + |x_3| + |x_4| + |x_5| &  \nonumber \\
{\rm{s.t.}} \ 85 x_1 + 92 x_2 + 45 x_3 + 27 x_4 + 31 x_5 & \geq 1 \nonumber \\
92 x_1 + 54 x_2 + 22 x_3 + 20 x_4 + 7 x_5 & \geq 1 \nonumber \\
96 x_1 + 67 x_2 + 29 x_3 + 20 x_4 + 11 x_5 & \geq 1 \nonumber \\
-91 x_1 - 57 x_2 - 33 x_3 - 23 x_4 - 12 x_5 & \geq 1 \nonumber \\
-99 x_1 - 75 x_2 - 26 x_3 - 24 x_4 - 41 x_5 & \geq 1 \nonumber \\
-98 x_1 - 99 x_2 - 57 x_3 - 45 x_4 - 65 x_5 & \geq 1 \nonumber
\end{align}

In this optimization problem $\textbf{(OP)}$, we wish to minimize the sum of absolute values of the decision variables. Such problems are useful when the decision variables might take both positive and negative values, and we want to optimize the magnitudes of the decision variables. 

We will now consider two possible ways to solve this problem. 

$\textbf{Approach 1:}$ 

We can use a substitution of the absolute function values of the variables to new variables as $u_i = |x_i|, \ \forall i \in \{1,\ldots,5\}$. With this substitution, note that we have $u_i\geq 0, \ \forall i \in \{1,\ldots,5\}$. Also, the following inequalities are satisfied: $x_i \leq u_i, -x_i \leq u_i, \ \forall i \in \{1,\ldots,5\}$. Thus we can transform the problem $\textbf{(OP)}$ as the following optimization problem $\textbf{(OP1)}$, where the absolute values of $x_i$ are replaced with $u_i$ and constraints related to the new variables $u_i$ are introduced. Thus we have the problem $\textbf{(OP1)}$:

\begin{align}
\min \ u_1 + u_2 + u_3 + u_4 + u_5 &  \nonumber \\
{\rm{s.t.}} \ 85 x_1 + 92 x_2 + 45 x_3 + 27 x_4 + 31 x_5 & \geq 1 \nonumber \\
92 x_1 + 54 x_2 + 22 x_3 + 20 x_4 + 7 x_5 & \geq 1 \nonumber \\
96 x_1 + 67 x_2 + 29 x_3 + 20 x_4 + 11 x_5 & \geq 1 \nonumber \\
-91 x_1 - 57 x_2 - 33 x_3 - 23 x_4 - 12 x_5 & \geq 1 \nonumber \\
-99 x_1 - 75 x_2 - 26 x_3 - 24 x_4 - 41 x_5 & \geq 1 \nonumber \\
-98 x_1 - 99 x_2 - 57 x_3 - 45 x_4 - 65 x_5 & \geq 1 \nonumber \\
u_i \geq x_i, & \  \forall i \in \{1,\ldots,5\} \nonumber \\ 
u_i \geq -x_i, & \  \forall i \in \{1,\ldots,5\} \nonumber \\ 
u_i \geq 0, & \ \forall i \in \{1,\ldots,5\}. 
\end{align}

Note that the number of decision variables in $\textbf{(OP1)}$ is twice the number of decision variables in $\textbf{(OP)}$. However the objective function and the constraints in $\textbf{(OP1)}$ are now linear since it doesn't contain any non linear function, and thus $\textbf{(OP1)}$ is a linear program. 


In [1]:
#Installing pyomo
! pip install -q pyomo

     |████████████████████████████████| 9.1 MB 5.3 MB/s 
     |████████████████████████████████| 49 kB 5.5 MB/s 


In [2]:
#importing required packages 
from pyomo.environ import * 
import numpy as np

In [4]:
df = np.loadtxt('lab6_coef.txt', delimiter=',')

In [5]:
model = ConcreteModel()

In [6]:
N = df.shape[1]-1
M = df.shape[0]-1

In [7]:
obj_df = df[0,:-1]
constr_df = df[1:,:-1]
constr_rhs = df[1:,-1]

In [8]:
column_ind_x = np.arange(int(N/2))
model.x = Var(column_ind_x)

In [9]:
column_ind_u = np.arange(int(N/2))
model.u = Var(column_ind_u, domain=NonNegativeReals)

In [10]:
row_indices = np.arange(M)

In [11]:
model.constraints = ConstraintList()

In [12]:
model.obj = Objective(expr = summation(obj_df[0:int(N/2)],model.x) + summation(obj_df[int(N/2):N],model.u), sense=minimize)

In [13]:
for i in row_indices:
  model.constraints.add(summation(constr_df[i][0:int(N/2)],model.x) + summation(constr_df[i][int(N/2):N],model.u)  >= constr_rhs[i])

In [14]:
model.pprint()

3 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   16 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
    u_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {0, 1, 2, 3, 4}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {0, 1, 2, 3, 4}

2 Var Declarations
    u : Size=5, Index=u_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :  None : False :  True : NonNegativeReals
          1 :     0 :  None :  None : False :  True : NonNegativeReals
          2 :     0 :  None :  None : False :  True : NonNegativeReals
          3 :     0 :  None :  None : False :  True : NonNegativeReals
          4 :     0 :  None :  None : False :  True : NonNegativeReals
    x : Siz

In [15]:
!apt-get install -y -qq coinor-cbc

Selecting previously unselected package coinor-libcoinutils3v5.
(Reading database ... 155047 files and directories currently installed.)
Preparing to unpack .../0-coinor-libcoinutils3v5_2.10.14+repack1-1_amd64.deb ...
Unpacking coinor-libcoinutils3v5 (2.10.14+repack1-1) ...
Selecting previously unselected package coinor-libosi1v5.
Preparing to unpack .../1-coinor-libosi1v5_0.107.9+repack1-1_amd64.deb ...
Unpacking coinor-libosi1v5 (0.107.9+repack1-1) ...
Selecting previously unselected package coinor-libclp1.
Preparing to unpack .../2-coinor-libclp1_1.16.11+repack1-1_amd64.deb ...
Unpacking coinor-libclp1 (1.16.11+repack1-1) ...
Selecting previously unselected package coinor-libcgl1.
Preparing to unpack .../3-coinor-libcgl1_0.59.10+repack1-1_amd64.deb ...
Unpacking coinor-libcgl1 (0.59.10+repack1-1) ...
Selecting previously unselected package coinor-libcbc3.
Preparing to unpack .../4-coinor-libcbc3_2.9.9+repack1-1_amd64.deb ...
Unpacking coinor-libcbc3 (2.9.9+repack1-1) ...
Selecting p

In [16]:
opt_cbc = SolverFactory('cbc')
result = opt_cbc.solve(model)

Ex-1.2

In [17]:
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


Yes, the solver yields optimal solution.

Ex-1.3

In [18]:
print('Objective Function Value = ', model.obj())

Objective Function Value =  0.547955725


In [19]:
print('Decision Variables: ')
for j in column_ind_x:
    print('x[',j,']:', model.x[j].value)
for j in column_ind_u:
    print('u[',j,']:', model.u[j].value)

Decision Variables: 
x[ 0 ]: -0.046448575
x[ 1 ]: 0.18612441
x[ 2 ]: -0.17131802
x[ 3 ]: 0.0
x[ 4 ]: -0.14406472
u[ 0 ]: 0.046448575
u[ 1 ]: 0.18612441
u[ 2 ]: 0.17131802
u[ 3 ]: 0.0
u[ 4 ]: 0.14406472


In [20]:
print('Constraints: ')
model.constraints.display()

Constraints: 
constraints : Size=16
    Key : Lower : Body               : Upper
      1 :   1.0 : 0.9999996250000001 :  None
      2 :   1.0 : 0.9999997599999997 :  None
      3 :   1.0 :  1.458337769999999 :  None
      4 :   1.0 : 1.0000002550000002 :  None
      5 :   1.0 :  1.000000215000001 :  None
      6 :   1.0 : 5.2549776999999995 :  None
      7 :   0.0 :         0.09289715 :  None
      8 :   0.0 :                0.0 :  None
      9 :   0.0 :         0.34263604 :  None
     10 :   0.0 :                0.0 :  None
     11 :   0.0 :         0.28812944 :  None
     12 :   0.0 :                0.0 :  None
     13 :   0.0 :         0.37224882 :  None
     14 :   0.0 :                0.0 :  None
     15 :   0.0 :                0.0 :  None
     16 :   0.0 :                0.0 :  None


Recall our optimization problem $\textbf{(OP)}$:
\begin{align}
\min \ |x_1| + |x_2| + |x_3| + |x_4| + |x_5| &  \nonumber \\
{\rm{s.t.}} \ 85 x_1 + 92 x_2 + 45 x_3 + 27 x_4 + 31 x_5 & \geq 1 \nonumber \\
92 x_1 + 54 x_2 + 22 x_3 + 20 x_4 + 7 x_5 & \geq 1 \nonumber \\
96 x_1 + 67 x_2 + 29 x_3 + 20 x_4 + 11 x_5 & \geq 1 \nonumber \\
-91 x_1 - 57 x_2 - 33 x_3 - 23 x_4 - 12 x_5 & \geq 1 \nonumber \\
-99 x_1 - 75 x_2 - 26 x_3 - 24 x_4 - 41 x_5 & \geq 1 \nonumber \\
-98 x_1 - 99 x_2 - 57 x_3 - 45 x_4 - 65 x_5 & \geq 1 \nonumber
\end{align}

Now we will consider a different approach to make the problem $\textbf{(OP)}$ linear. 

$\textbf{Approach 2:}$

In this approach we will use some fundamental properties of real numbers. Indeed, for any real number $x$, we can write $x=a-b$ where $a\geq 0, b\geq 0$. 

Hence we can substitute $|x| = |a-b|, \ a\geq 0, b\geq 0$. 

Now we will consider another interesting property of real numbers: 
$|u-v| = u+v \iff u\geq 0, v\geq 0, uv = 0$. 

Using this property we can write $|x| = a+b, \ a\geq 0, \ b\geq 0$. Note that this replacement will imply that $ab=0$. 

Thus we can transform the optimization problem $\textbf{(OP)}$ into a new optimization problem $\textbf{(OP2)}$ where $x_i = a_i - b_i, \text{ and } |x_i| = a_i + b_i, \ \forall i \in \{1,\dots,5\}$ where $a_i \geq 0, b_i \geq 0, \forall i \in \{1,\dots,5\}$. Thus we have the new optimization problem $\textbf{(OP2)}$: 

\begin{align}
\min \ (a_1 + b_1) +  (a_2 + b_2) + (a_3 + b_3) + (a_4 + b_4) + (a_5 + b_5) &  \nonumber \\
{\rm{s.t.}} \ 85 (a_1-b_1) + 92 (a_2-b_2) + 45 (a_3-b_3) + 27 (a_4-b_4) + 31 (a_5-b_5) & \geq 1 \nonumber \\
92 (a_1-b_1) + 54 (a_2-b_2) + 22 (a_3-b_3) + 20 (a_4-b_4) + 7 (a_5-b_5) & \geq 1 \nonumber \\
96 (a_1-b_1) + 67 (a_2-b_2) + 29 (a_3-b_3) + 20 (a_4-b_4) + 11 (a_5-b_5) & \geq 1 \nonumber \\
-91 (a_1-b_1) - 57 (a_2-b_2) - 33 (a_3-b_3) - 23 (a_4-b_4) - 12 (a_5-b_5) & \geq 1 \nonumber \\
-99 (a_1-b_1) - 75 (a_2-b_2) - 26 (a_3-b_3) - 24 (a_4-b_4) - 41 (a_5-b_5) & \geq 1 \nonumber \\
-98 (a_1-b_1) - 99 (a_2-b_2) - 57 (a_3-b_3) - 45 (a_4-b_4) - 65 (a_5-b_5) & \geq 1 \nonumber \\ 
a_i \geq 0, \ b_i \geq 0, & \ \forall i \in \{1,\ldots,5\}. \nonumber 
\end{align}

Ex-1.6:

In [22]:
df_1 = np.loadtxt('lab6_practice_coef_OP2.txt',delimiter=',')

Ex-1.7:

In [23]:
print(df_1.shape)
print('Num rows:',df_1.shape[0])
print('Num cols:',df_1.shape[1])

(7, 11)
Num rows: 7
Num cols: 11


In [24]:
print(df_1)

[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   0.]
 [ 85.  92.  45.  27.  31. -85. -92. -45. -27. -31.   1.]
 [ 92.  54.  22.  20.   7. -92. -54. -22. -20.  -7.   1.]
 [ 96.  67.  29.  20.  11. -96. -67. -29. -20. -11.   1.]
 [-91. -57. -33. -23. -12.  91.  57.  33.  23.  12.   1.]
 [-99. -75. -26. -24. -41.  99.  75.  26.  24.  41.   1.]
 [-98. -99. -57. -45. -65.  98.  99.  57.  45.  65.   1.]]


In [25]:
N = df_1.shape[1]-1
M=df_1.shape[0]-1

In [26]:
obj_df_1 = df_1[0,:-1]

In [27]:
constr_df_1 = df_1[1:,:-1]

In [28]:
rhs_df_1 = df_1[1:,-1]
print(rhs_df_1.shape)
print(rhs_df_1)

(6,)
[1. 1. 1. 1. 1. 1.]


In [30]:
model_2 = ConcreteModel()
column_ind_a = np.arange(int(N/2))
model_2.a = Var(column_ind_a,domain=NonNegativeReals)
column_ind_b = np.arange(int(N/2))
model_2.b = Var(column_ind_b,domain=NonNegativeReals)
row_indices = np.arange(M)
model_2.constraints = ConstraintList()
model_2.obj = Objective(expr = summation(obj_df_1[0:int(N/2)],model_2.a) + summation(obj_df_1[int(N/2):N],model_2.b), sense=minimize)
for i in row_indices:
  model_2.constraints.add(summation(constr_df_1[i][0:int(N/2)],model_2.a) + summation(constr_df_1[i][int(N/2):N],model_2.b)  >= rhs_df_1[i])

In [31]:
model_2.pprint()

3 Set Declarations
    a_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {0, 1, 2, 3, 4}
    b_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {0, 1, 2, 3, 4}
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    6 : {1, 2, 3, 4, 5, 6}

2 Var Declarations
    a : Size=5, Index=a_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :  None : False :  True : NonNegativeReals
          1 :     0 :  None :  None : False :  True : NonNegativeReals
          2 :     0 :  None :  None : False :  True : NonNegativeReals
          3 :     0 :  None :  None : False :  True : NonNegativeReals
          4 :     0 :  None :  None : False :  True : NonNegativeReals
    b : Size=5, Index=b_index
        Key : Lowe

Ex-1.8:

In [32]:
result = opt_cbc.solve(model_2)

Ex-1.9:

In [33]:
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


Ex-1.10:

In [34]:
print('\n Objective = ', model_2.obj())


 Objective =  0.547955725


In [35]:
print('Values of Decision Variables : ')
for j in column_ind_a:
    print('a[',j,']:', model_2.a[j].value)
for j in column_ind_b:
    print('b[',j,']:', model_2.b[j].value)

Values of Decision Variables : 
a[ 0 ]: 0.0
a[ 1 ]: 0.18612441
a[ 2 ]: 0.0
a[ 3 ]: 0.0
a[ 4 ]: 0.0
b[ 0 ]: 0.046448575
b[ 1 ]: 0.0
b[ 2 ]: 0.17131802
b[ 3 ]: 0.0
b[ 4 ]: 0.14406472


In [36]:
print('Constraints : ')
model_2.constraints.display()

Constraints : 
constraints : Size=6
    Key : Lower : Body               : Upper
      1 :   1.0 :  0.999999625000001 :  None
      2 :   1.0 : 0.9999997599999997 :  None
      3 :   1.0 :         1.45833777 :  None
      4 :   1.0 : 1.0000002549999998 :  None
      5 :   1.0 :        1.000000215 :  None
      6 :   1.0 :  5.254977699999998 :  None


Constraints 1,2,4,5 are active while the constraints 3,6 are inactive.

Ex-1.11:

In [38]:
model_2.x = Var(column_ind_a)

In [39]:
 for i in column_ind_b:
    model_2.x[i].value=model_2.a[i].value-model_2.b[i].value

In [40]:
print('Original Decision Variables: ')
for i in column_ind_a:
     print('x[',i,']:', model_2.x[i].value)

Original Decision Variables: 
x[ 0 ]: -0.046448575
x[ 1 ]: 0.18612441
x[ 2 ]: -0.17131802
x[ 3 ]: 0.0
x[ 4 ]: -0.14406472


Ex-1.12:

The values of $x_i's$ are obtained same from both the approaches since both the models are transformations of same model. 

In [41]:
print('Original Decision Variables x(i) for OP1:')
for j in column_ind_x:
    print('x[',j,']:', model.x[j].value)
print('Original Decision Variables x(i) for OP2:')
for i in column_ind_a:
    print('x[',i,']:', model_2.x[i].value)

Original Decision Variables x(i) for OP1:
x[ 0 ]: -0.046448575
x[ 1 ]: 0.18612441
x[ 2 ]: -0.17131802
x[ 3 ]: 0.0
x[ 4 ]: -0.14406472
Original Decision Variables x(i) for OP2:
x[ 0 ]: -0.046448575
x[ 1 ]: 0.18612441
x[ 2 ]: -0.17131802
x[ 3 ]: 0.0
x[ 4 ]: -0.14406472
